aggiunto MCAD, primo esonero 2021
stefa168/guida_degli_studenti_di pull request #23
Opened 2021-12-27 16:59 UTC by lory9894

Ho un po' di roba che posso mergare, perchè sono un data hoarder. con calma durante le vacanze faccio qualche push

2021-12-27 16:59 UTC, lory9894 commented
helps with issue #7

2021-12-27 17:00 UTC, stefa168 commented
@lory9894 Ottimo, teniamo aperta questa PR allora!

2022-01-03 10:04 UTC, federicotorrielli commented
@lory9894 A che punto siamo? Hai altro da aggiungere?

2022-01-03 10:39 UTC, stefa168 commented
@federicotorrielli Se deve essere aggiunto altro, consiglio di indicare la PR come bozza, così rimane qui e non possiamo accettare la merge

2022-01-03 11:29 UTC, lory9894 commented
@federicotorrielli direi che va bene.
Ho ancora da aggiungere ArchII ma sto aspettando che il prof finisca il corso in modo da avere un riassunto completo.
Ho una marea di altri appunti, però sono tutti scritti a mano e male; sarebbero più uno spreco di spazio che altro

2022-01-04 08:03 UTC, federicotorrielli commented
@lory9894 Preferirei non aggiungere appunti a mano, ma se hai voglia/tempo di trascriverne qualcuno in md o altro formato sarebbe sicuramente utile per tutti! In ogni caso, metti come bozza questa PR, e sbloccala e notificaci quando hai finito.

2022-01-06 08:49 UTC, lory9894 commented
Pronta per la review, scusare per il bordello con i commit.

2022-01-06 09:06 UTC, stefa168 commented
@lory9894 Ci mancherebbe, faccio oggi appena mi riprendo 👍

2022-01-06 11:22 UTC, stefa168 requested changes
## MCAD
Il file dell'esonero del 30 Novembre è da spostare in una cartella "Esami"
## Storia dell'Informatica
- Stessa cosa di MCAD, sono da raggruppare per data e riordinare in una cartella apposita per gli esami
- Il file ESONERO_scritto_prima_parte_Storia_dell'Informatica_18_12_2020_.png contiene informazioni sensibili (nome dello studente in cima alla pagina; è da modificare tagliando quella parte
- Il file Materie/STORIA/Esame parte2/17_02_2020.pdf è praticamente illeggibile, sarebbe utile una versione più ad alta risoluzione; alternativamente può anche non essere caricato.
- Il file Materie/STORIA/appunti/Ripasso_2020-2021 non ha un'estensione e non riesco ad identificare quale genere di file sia. Sarebbe utile una correzione anche qui...

2022-01-07 11:04 UTC, federicotorrielli commented
@stefa168 Ora mi pare tutto a posto ma lascio l'ultima a te

2022-01-07 11:06 UTC, stefa168 approved these changes

2022-01-07 11:06 UTC, merged